[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.flake8]
exclude = """
bd_tools/src/bd_tools/recorder,
bd_tools/src/bd_tools/dev,
bd_tools/bd_tools.egg-info,
bd_tools/build,
"""
extend-ignore = "E203,"
