// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util/comms/motor_server/motor_control.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto;
namespace motor {
class MotorCommand;
class MotorCommandDefaultTypeInternal;
extern MotorCommandDefaultTypeInternal _MotorCommand_default_instance_;
class MotorCommandBatch;
class MotorCommandBatchDefaultTypeInternal;
extern MotorCommandBatchDefaultTypeInternal _MotorCommandBatch_default_instance_;
class MotorStatus;
class MotorStatusDefaultTypeInternal;
extern MotorStatusDefaultTypeInternal _MotorStatus_default_instance_;
class MotorStatusBatch;
class MotorStatusBatchDefaultTypeInternal;
extern MotorStatusBatchDefaultTypeInternal _MotorStatusBatch_default_instance_;
}  // namespace motor
PROTOBUF_NAMESPACE_OPEN
template<> ::motor::MotorCommand* Arena::CreateMaybeMessage<::motor::MotorCommand>(Arena*);
template<> ::motor::MotorCommandBatch* Arena::CreateMaybeMessage<::motor::MotorCommandBatch>(Arena*);
template<> ::motor::MotorStatus* Arena::CreateMaybeMessage<::motor::MotorStatus>(Arena*);
template<> ::motor::MotorStatusBatch* Arena::CreateMaybeMessage<::motor::MotorStatusBatch>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace motor {

// ===================================================================

class MotorCommand PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:motor.MotorCommand) */ {
 public:
  inline MotorCommand() : MotorCommand(nullptr) {};
  virtual ~MotorCommand();

  MotorCommand(const MotorCommand& from);
  MotorCommand(MotorCommand&& from) noexcept
    : MotorCommand() {
    *this = ::std::move(from);
  }

  inline MotorCommand& operator=(const MotorCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorCommand& operator=(MotorCommand&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MotorCommand& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MotorCommand* internal_default_instance() {
    return reinterpret_cast<const MotorCommand*>(
               &_MotorCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MotorCommand& a, MotorCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorCommand* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MotorCommand* New() const final {
    return CreateMaybeMessage<MotorCommand>(nullptr);
  }

  MotorCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MotorCommand>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MotorCommand& from);
  void MergeFrom(const MotorCommand& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "motor.MotorCommand";
  }
  protected:
  explicit MotorCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto);
    return ::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValuesFieldNumber = 3,
    kModeFieldNumber = 2,
    kTimestampFieldNumber = 4,
    kBoardIdFieldNumber = 1,
  };
  // repeated float values = 3;
  int values_size() const;
  private:
  int _internal_values_size() const;
  public:
  void clear_values();
  private:
  float _internal_values(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_values() const;
  void _internal_add_values(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_values();
  public:
  float values(int index) const;
  void set_values(int index, float value);
  void add_values(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      values() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_values();

  // string mode = 2;
  void clear_mode();
  const std::string& mode() const;
  void set_mode(const std::string& value);
  void set_mode(std::string&& value);
  void set_mode(const char* value);
  void set_mode(const char* value, size_t size);
  std::string* mutable_mode();
  std::string* release_mode();
  void set_allocated_mode(std::string* mode);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_mode();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_mode(
      std::string* mode);
  private:
  const std::string& _internal_mode() const;
  void _internal_set_mode(const std::string& value);
  std::string* _internal_mutable_mode();
  public:

  // uint64 timestamp = 4;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 board_id = 1;
  void clear_board_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 board_id() const;
  void set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_board_id() const;
  void _internal_set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:motor.MotorCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > values_;
  mutable std::atomic<int> _values_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mode_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint32 board_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class MotorStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:motor.MotorStatus) */ {
 public:
  inline MotorStatus() : MotorStatus(nullptr) {};
  virtual ~MotorStatus();

  MotorStatus(const MotorStatus& from);
  MotorStatus(MotorStatus&& from) noexcept
    : MotorStatus() {
    *this = ::std::move(from);
  }

  inline MotorStatus& operator=(const MotorStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorStatus& operator=(MotorStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MotorStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MotorStatus* internal_default_instance() {
    return reinterpret_cast<const MotorStatus*>(
               &_MotorStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MotorStatus& a, MotorStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MotorStatus* New() const final {
    return CreateMaybeMessage<MotorStatus>(nullptr);
  }

  MotorStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MotorStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MotorStatus& from);
  void MergeFrom(const MotorStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "motor.MotorStatus";
  }
  protected:
  explicit MotorStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto);
    return ::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 3,
    kBoardIdFieldNumber = 1,
    kSuccessFieldNumber = 2,
    kTimestampFieldNumber = 4,
  };
  // string error_message = 3;
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // uint32 board_id = 1;
  void clear_board_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 board_id() const;
  void set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_board_id() const;
  void _internal_set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // uint64 timestamp = 4;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:motor.MotorStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  ::PROTOBUF_NAMESPACE_ID::uint32 board_id_;
  bool success_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class MotorCommandBatch PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:motor.MotorCommandBatch) */ {
 public:
  inline MotorCommandBatch() : MotorCommandBatch(nullptr) {};
  virtual ~MotorCommandBatch();

  MotorCommandBatch(const MotorCommandBatch& from);
  MotorCommandBatch(MotorCommandBatch&& from) noexcept
    : MotorCommandBatch() {
    *this = ::std::move(from);
  }

  inline MotorCommandBatch& operator=(const MotorCommandBatch& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorCommandBatch& operator=(MotorCommandBatch&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MotorCommandBatch& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MotorCommandBatch* internal_default_instance() {
    return reinterpret_cast<const MotorCommandBatch*>(
               &_MotorCommandBatch_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MotorCommandBatch& a, MotorCommandBatch& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorCommandBatch* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorCommandBatch* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MotorCommandBatch* New() const final {
    return CreateMaybeMessage<MotorCommandBatch>(nullptr);
  }

  MotorCommandBatch* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MotorCommandBatch>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MotorCommandBatch& from);
  void MergeFrom(const MotorCommandBatch& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorCommandBatch* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "motor.MotorCommandBatch";
  }
  protected:
  explicit MotorCommandBatch(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto);
    return ::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandsFieldNumber = 1,
  };
  // repeated .motor.MotorCommand commands = 1;
  int commands_size() const;
  private:
  int _internal_commands_size() const;
  public:
  void clear_commands();
  ::motor::MotorCommand* mutable_commands(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorCommand >*
      mutable_commands();
  private:
  const ::motor::MotorCommand& _internal_commands(int index) const;
  ::motor::MotorCommand* _internal_add_commands();
  public:
  const ::motor::MotorCommand& commands(int index) const;
  ::motor::MotorCommand* add_commands();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorCommand >&
      commands() const;

  // @@protoc_insertion_point(class_scope:motor.MotorCommandBatch)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorCommand > commands_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class MotorStatusBatch PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:motor.MotorStatusBatch) */ {
 public:
  inline MotorStatusBatch() : MotorStatusBatch(nullptr) {};
  virtual ~MotorStatusBatch();

  MotorStatusBatch(const MotorStatusBatch& from);
  MotorStatusBatch(MotorStatusBatch&& from) noexcept
    : MotorStatusBatch() {
    *this = ::std::move(from);
  }

  inline MotorStatusBatch& operator=(const MotorStatusBatch& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorStatusBatch& operator=(MotorStatusBatch&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MotorStatusBatch& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MotorStatusBatch* internal_default_instance() {
    return reinterpret_cast<const MotorStatusBatch*>(
               &_MotorStatusBatch_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MotorStatusBatch& a, MotorStatusBatch& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorStatusBatch* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorStatusBatch* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MotorStatusBatch* New() const final {
    return CreateMaybeMessage<MotorStatusBatch>(nullptr);
  }

  MotorStatusBatch* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MotorStatusBatch>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MotorStatusBatch& from);
  void MergeFrom(const MotorStatusBatch& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorStatusBatch* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "motor.MotorStatusBatch";
  }
  protected:
  explicit MotorStatusBatch(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto);
    return ::descriptor_table_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusesFieldNumber = 1,
  };
  // repeated .motor.MotorStatus statuses = 1;
  int statuses_size() const;
  private:
  int _internal_statuses_size() const;
  public:
  void clear_statuses();
  ::motor::MotorStatus* mutable_statuses(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorStatus >*
      mutable_statuses();
  private:
  const ::motor::MotorStatus& _internal_statuses(int index) const;
  ::motor::MotorStatus* _internal_add_statuses();
  public:
  const ::motor::MotorStatus& statuses(int index) const;
  ::motor::MotorStatus* add_statuses();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorStatus >&
      statuses() const;

  // @@protoc_insertion_point(class_scope:motor.MotorStatusBatch)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorStatus > statuses_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MotorCommand

// uint32 board_id = 1;
inline void MotorCommand::clear_board_id() {
  board_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorCommand::_internal_board_id() const {
  return board_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorCommand::board_id() const {
  // @@protoc_insertion_point(field_get:motor.MotorCommand.board_id)
  return _internal_board_id();
}
inline void MotorCommand::_internal_set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  board_id_ = value;
}
inline void MotorCommand::set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_board_id(value);
  // @@protoc_insertion_point(field_set:motor.MotorCommand.board_id)
}

// string mode = 2;
inline void MotorCommand::clear_mode() {
  mode_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MotorCommand::mode() const {
  // @@protoc_insertion_point(field_get:motor.MotorCommand.mode)
  return _internal_mode();
}
inline void MotorCommand::set_mode(const std::string& value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:motor.MotorCommand.mode)
}
inline std::string* MotorCommand::mutable_mode() {
  // @@protoc_insertion_point(field_mutable:motor.MotorCommand.mode)
  return _internal_mutable_mode();
}
inline const std::string& MotorCommand::_internal_mode() const {
  return mode_.Get();
}
inline void MotorCommand::_internal_set_mode(const std::string& value) {
  
  mode_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MotorCommand::set_mode(std::string&& value) {
  
  mode_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:motor.MotorCommand.mode)
}
inline void MotorCommand::set_mode(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mode_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:motor.MotorCommand.mode)
}
inline void MotorCommand::set_mode(const char* value,
    size_t size) {
  
  mode_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:motor.MotorCommand.mode)
}
inline std::string* MotorCommand::_internal_mutable_mode() {
  
  return mode_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MotorCommand::release_mode() {
  // @@protoc_insertion_point(field_release:motor.MotorCommand.mode)
  return mode_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MotorCommand::set_allocated_mode(std::string* mode) {
  if (mode != nullptr) {
    
  } else {
    
  }
  mode_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mode,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:motor.MotorCommand.mode)
}
inline std::string* MotorCommand::unsafe_arena_release_mode() {
  // @@protoc_insertion_point(field_unsafe_arena_release:motor.MotorCommand.mode)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return mode_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void MotorCommand::unsafe_arena_set_allocated_mode(
    std::string* mode) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (mode != nullptr) {
    
  } else {
    
  }
  mode_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      mode, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:motor.MotorCommand.mode)
}

// repeated float values = 3;
inline int MotorCommand::_internal_values_size() const {
  return values_.size();
}
inline int MotorCommand::values_size() const {
  return _internal_values_size();
}
inline void MotorCommand::clear_values() {
  values_.Clear();
}
inline float MotorCommand::_internal_values(int index) const {
  return values_.Get(index);
}
inline float MotorCommand::values(int index) const {
  // @@protoc_insertion_point(field_get:motor.MotorCommand.values)
  return _internal_values(index);
}
inline void MotorCommand::set_values(int index, float value) {
  values_.Set(index, value);
  // @@protoc_insertion_point(field_set:motor.MotorCommand.values)
}
inline void MotorCommand::_internal_add_values(float value) {
  values_.Add(value);
}
inline void MotorCommand::add_values(float value) {
  _internal_add_values(value);
  // @@protoc_insertion_point(field_add:motor.MotorCommand.values)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MotorCommand::_internal_values() const {
  return values_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MotorCommand::values() const {
  // @@protoc_insertion_point(field_list:motor.MotorCommand.values)
  return _internal_values();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MotorCommand::_internal_mutable_values() {
  return &values_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MotorCommand::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:motor.MotorCommand.values)
  return _internal_mutable_values();
}

// uint64 timestamp = 4;
inline void MotorCommand::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorCommand::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorCommand::timestamp() const {
  // @@protoc_insertion_point(field_get:motor.MotorCommand.timestamp)
  return _internal_timestamp();
}
inline void MotorCommand::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  timestamp_ = value;
}
inline void MotorCommand::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:motor.MotorCommand.timestamp)
}

// -------------------------------------------------------------------

// MotorStatus

// uint32 board_id = 1;
inline void MotorStatus::clear_board_id() {
  board_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorStatus::_internal_board_id() const {
  return board_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorStatus::board_id() const {
  // @@protoc_insertion_point(field_get:motor.MotorStatus.board_id)
  return _internal_board_id();
}
inline void MotorStatus::_internal_set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  board_id_ = value;
}
inline void MotorStatus::set_board_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_board_id(value);
  // @@protoc_insertion_point(field_set:motor.MotorStatus.board_id)
}

// bool success = 2;
inline void MotorStatus::clear_success() {
  success_ = false;
}
inline bool MotorStatus::_internal_success() const {
  return success_;
}
inline bool MotorStatus::success() const {
  // @@protoc_insertion_point(field_get:motor.MotorStatus.success)
  return _internal_success();
}
inline void MotorStatus::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void MotorStatus::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:motor.MotorStatus.success)
}

// string error_message = 3;
inline void MotorStatus::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MotorStatus::error_message() const {
  // @@protoc_insertion_point(field_get:motor.MotorStatus.error_message)
  return _internal_error_message();
}
inline void MotorStatus::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:motor.MotorStatus.error_message)
}
inline std::string* MotorStatus::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:motor.MotorStatus.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& MotorStatus::_internal_error_message() const {
  return error_message_.Get();
}
inline void MotorStatus::_internal_set_error_message(const std::string& value) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MotorStatus::set_error_message(std::string&& value) {
  
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:motor.MotorStatus.error_message)
}
inline void MotorStatus::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:motor.MotorStatus.error_message)
}
inline void MotorStatus::set_error_message(const char* value,
    size_t size) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:motor.MotorStatus.error_message)
}
inline std::string* MotorStatus::_internal_mutable_error_message() {
  
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MotorStatus::release_error_message() {
  // @@protoc_insertion_point(field_release:motor.MotorStatus.error_message)
  return error_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MotorStatus::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:motor.MotorStatus.error_message)
}
inline std::string* MotorStatus::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:motor.MotorStatus.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void MotorStatus::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:motor.MotorStatus.error_message)
}

// uint64 timestamp = 4;
inline void MotorStatus::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatus::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatus::timestamp() const {
  // @@protoc_insertion_point(field_get:motor.MotorStatus.timestamp)
  return _internal_timestamp();
}
inline void MotorStatus::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  timestamp_ = value;
}
inline void MotorStatus::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:motor.MotorStatus.timestamp)
}

// -------------------------------------------------------------------

// MotorCommandBatch

// repeated .motor.MotorCommand commands = 1;
inline int MotorCommandBatch::_internal_commands_size() const {
  return commands_.size();
}
inline int MotorCommandBatch::commands_size() const {
  return _internal_commands_size();
}
inline void MotorCommandBatch::clear_commands() {
  commands_.Clear();
}
inline ::motor::MotorCommand* MotorCommandBatch::mutable_commands(int index) {
  // @@protoc_insertion_point(field_mutable:motor.MotorCommandBatch.commands)
  return commands_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorCommand >*
MotorCommandBatch::mutable_commands() {
  // @@protoc_insertion_point(field_mutable_list:motor.MotorCommandBatch.commands)
  return &commands_;
}
inline const ::motor::MotorCommand& MotorCommandBatch::_internal_commands(int index) const {
  return commands_.Get(index);
}
inline const ::motor::MotorCommand& MotorCommandBatch::commands(int index) const {
  // @@protoc_insertion_point(field_get:motor.MotorCommandBatch.commands)
  return _internal_commands(index);
}
inline ::motor::MotorCommand* MotorCommandBatch::_internal_add_commands() {
  return commands_.Add();
}
inline ::motor::MotorCommand* MotorCommandBatch::add_commands() {
  // @@protoc_insertion_point(field_add:motor.MotorCommandBatch.commands)
  return _internal_add_commands();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorCommand >&
MotorCommandBatch::commands() const {
  // @@protoc_insertion_point(field_list:motor.MotorCommandBatch.commands)
  return commands_;
}

// -------------------------------------------------------------------

// MotorStatusBatch

// repeated .motor.MotorStatus statuses = 1;
inline int MotorStatusBatch::_internal_statuses_size() const {
  return statuses_.size();
}
inline int MotorStatusBatch::statuses_size() const {
  return _internal_statuses_size();
}
inline void MotorStatusBatch::clear_statuses() {
  statuses_.Clear();
}
inline ::motor::MotorStatus* MotorStatusBatch::mutable_statuses(int index) {
  // @@protoc_insertion_point(field_mutable:motor.MotorStatusBatch.statuses)
  return statuses_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorStatus >*
MotorStatusBatch::mutable_statuses() {
  // @@protoc_insertion_point(field_mutable_list:motor.MotorStatusBatch.statuses)
  return &statuses_;
}
inline const ::motor::MotorStatus& MotorStatusBatch::_internal_statuses(int index) const {
  return statuses_.Get(index);
}
inline const ::motor::MotorStatus& MotorStatusBatch::statuses(int index) const {
  // @@protoc_insertion_point(field_get:motor.MotorStatusBatch.statuses)
  return _internal_statuses(index);
}
inline ::motor::MotorStatus* MotorStatusBatch::_internal_add_statuses() {
  return statuses_.Add();
}
inline ::motor::MotorStatus* MotorStatusBatch::add_statuses() {
  // @@protoc_insertion_point(field_add:motor.MotorStatusBatch.statuses)
  return _internal_add_statuses();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::motor::MotorStatus >&
MotorStatusBatch::statuses() const {
  // @@protoc_insertion_point(field_list:motor.MotorStatusBatch.statuses)
  return statuses_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace motor

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_util_2fcomms_2fmotor_5fserver_2fmotor_5fcontrol_2eproto
