# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: motor_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'motor_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13motor_control.proto\x12\x05motor\"Q\n\x0cMotorCommand\x12\x10\n\x08\x62oard_id\x18\x01 \x01(\r\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\"Z\n\x0bMotorStatus\x12\x10\n\x08\x62oard_id\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\":\n\x11MotorCommandBatch\x12%\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x13.motor.MotorCommand\"8\n\x10MotorStatusBatch\x12$\n\x08statuses\x18\x01 \x03(\x0b\x32\x12.motor.MotorStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motor_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTORCOMMAND']._serialized_start=30
  _globals['_MOTORCOMMAND']._serialized_end=111
  _globals['_MOTORSTATUS']._serialized_start=113
  _globals['_MOTORSTATUS']._serialized_end=203
  _globals['_MOTORCOMMANDBATCH']._serialized_start=205
  _globals['_MOTORCOMMANDBATCH']._serialized_end=263
  _globals['_MOTORSTATUSBATCH']._serialized_start=265
  _globals['_MOTORSTATUSBATCH']._serialized_end=321
# @@protoc_insertion_point(module_scope)
