#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cstring>
#include <iostream>
#include <thread>
#include <vector>
#include <atomic>
#include <chrono>

#include "util/comms/board_manager.h"
#include "motor_control.pb.h" // Generated by Bazel
#include "circular_buffer.h"

// Shared memory settings
constexpr const char* kShmName = "/motor_server_shm";
constexpr size_t kShmSize = 65536; // 64 KB
constexpr size_t kBufSize = 32768; // 32 KB for each buffer

// Shared memory layout: [command buffer][status buffer]
struct SharedMemoryLayout {
    CircularBuffer<kBufSize> command_buf;
    CircularBuffer<kBufSize> status_buf;
};

// Helper: read a framed message ([uint32_t len][bytes]) from buffer
// Returns true if a full message was read
bool ReadFramedMessage(CircularBuffer<kBufSize>& buf, std::vector<uint8_t>& out) {
    uint8_t len_bytes[4];
    if (buf.Available() < 4) return false;
    // Peek length
    for (int i = 0; i < 4; ++i) {
        buf.Peek(len_bytes[i]);
        buf.Read(&len_bytes[i], 1);
    }
    uint32_t msg_len = 0;
    std::memcpy(&msg_len, len_bytes, 4);
    if (msg_len == 0 || msg_len > kBufSize - 4) return false;
    if (buf.Available() < msg_len) {
        // Not enough data yet
        // Put length bytes back (reverse order)
        for (int i = 3; i >= 0; --i) buf.Write(&len_bytes[i], 1);
        return false;
    }
    out.resize(msg_len);
    buf.Read(out.data(), msg_len);
    return true;
}

// Helper: write a framed message ([uint32_t len][bytes]) to buffer
bool WriteFramedMessage(CircularBuffer<kBufSize>& buf, const uint8_t* data, uint32_t len) {
    if (buf.Free() < len + 4) return false;
    uint8_t len_bytes[4];
    std::memcpy(len_bytes, &len, 4);
    buf.Write(len_bytes, 4);
    buf.Write(data, len);
    return true;
}

int main(int argc, char* argv[]) {
    // Example: parse serial port and baud rate from args (TODO: use real arg parsing)
    std::string serial_port = "/dev/ttyACM0";
    unsigned int baud_rate = 1000000;
    std::vector<uint8_t> board_ids = {1}; // TODO: make configurable

    // Set up BoardManager
    BoardManager manager(serial_port, baud_rate, board_ids);
    if (!manager.InitializeBoards()) {
        std::cerr << "Failed to initialize boards." << std::endl;
        return 1;
    }
    manager.InitializeMotorParameters();

    // Set up shared memory
    int shm_fd = shm_open(kShmName, O_CREAT | O_RDWR, 0666);
    if (shm_fd == -1) {
        std::cerr << "Failed to open shared memory: " << strerror(errno) << std::endl;
        return 1;
    }
    if (ftruncate(shm_fd, kShmSize) == -1) {
        std::cerr << "Failed to set shared memory size: " << strerror(errno) << std::endl;
        return 1;
    }
    void* shm_ptr = mmap(nullptr, kShmSize, PROT_READ | PROT_WRITE, MAP_SHARED, shm_fd, 0);
    if (shm_ptr == MAP_FAILED) {
        std::cerr << "Failed to mmap shared memory: " << strerror(errno) << std::endl;
        return 1;
    }
    auto* shm = reinterpret_cast<SharedMemoryLayout*>(shm_ptr);

    std::cout << "Motor server started. Waiting for commands..." << std::endl;

    // Main loop: poll for commands, execute, write status
    while (true) {
        std::vector<uint8_t> msg_bytes;
        if (ReadFramedMessage(shm->command_buf, msg_bytes)) {
            motor::MotorCommand cmd;
            if (!cmd.ParseFromArray(msg_bytes.data(), msg_bytes.size())) {
                std::cerr << "Malformed MotorCommand protobuf!" << std::endl;
                continue;
            }
            // Execute command
            bool ok = false;
            std::string error;
            try {
                ok = manager.DriveMotor(cmd.board_id(), cmd.mode(), {cmd.values().begin(), cmd.values().end()});
            } catch (const std::exception& e) {
                ok = false;
                error = e.what();
            }
            // Prepare status
            motor::MotorStatus status;
            status.set_board_id(cmd.board_id());
            status.set_success(ok);
            status.set_error_message(error);
            status.set_timestamp(cmd.timestamp());
            // Serialize and write status
            std::vector<uint8_t> status_bytes(status.ByteSizeLong());
            if (!status.SerializeToArray(status_bytes.data(), status_bytes.size())) {
                std::cerr << "Failed to serialize MotorStatus!" << std::endl;
                continue;
            }
            if (!WriteFramedMessage(shm->status_buf, status_bytes.data(), status_bytes.size())) {
                std::cerr << "Status buffer full, dropping status!" << std::endl;
            }
        } else {
            std::this_thread::sleep_for(std::chrono::milliseconds(2));
        }
    }

    // Cleanup (never reached in this skeleton)
    munmap(shm_ptr, kShmSize);
    close(shm_fd);
    shm_unlink(kShmName);
    return 0;
} 