#ifndef _HW_CONF_H_
#define _HW_CONF_H_

#define CURR_A_CHANNEL ADC_CHANNEL_IN12
#define CURR_B_CHANNEL ADC_CHANNEL_IN11
#define CURR_C_CHANNEL ADC_CHANNEL_IN10

#define VBUS_CHANNEL ADC_CHANNEL_IN13

#define VSENSE_A_CHANNEL ADC_CHANNEL_IN8
#define VSENSE_B_CHANNEL ADC_CHANNEL_IN15
#define VSENSE_C_CHANNEL ADC_CHANNEL_IN14

#endif /* _HW_CONF_H_ */
